#!/bin/bash
# Assuming it is running on Debian

# Variables:
ARCH=x64
NODE_VERSION=12.13.0

# Step 1: Install Dependencies
sudo npm install -g nexe
sudo apt-get install -y ruby ruby-dev rubygems build-essential rpm
sudo gem install --no-ri --no-rdoc fpm

# Step 2: Prepare Folders and Files
mkdir -p .build/scripts
cp ./scripts/linux/after-upgrade .build/scripts/after-upgrade
cp ./scripts/linux/before-remove .build/scripts/before-remove
cp ./scripts/linux/init-script .build/scripts/init-script
cp ./scripts/linux/logrotate .build/scripts/logrotate

# Step 3: Compile and Build Executable
nexe -i index.js -o .build/logdna-agent -t linux-${ARCH}-${NODE_VERSION}

# Step 4: Debian Packaging
fpm --input-type ${INPUT_TYPE} --output-type ${DEBIAN} --name ${NAME} --version ${VERSION} --license ${LICENSE} --vendor ${VENDOR} --description ${DESCRIPTION} --url ${URL} --maintainer ${MAINTAINER} --before-remove ./.build/scripts/before-remove --after-upgrade ./.build/scripts/after-upgrade --force --deb-no-default-config-files ./.build/logdna-agent=/usr/bin/logdna-agent ./.build/scripts/init-script=/etc/init.d/logdna-agent ./.build/scripts/logrotate=/etc/logrotate.d/logdna-agent

# Step 5: RedHat Packaging
fpm --input-type ${INPUT_TYPE} --output-type ${REDHAT} --name ${NAME} --version ${VERSION} --license ${LICENSE} --vendor ${VENDOR} --description ${DESCRIPTION} --url ${URL} --maintainer ${MAINTAINER} --before-remove ./.build/scripts/before-remove --after-upgrade ./.build/scripts/after-upgrade --force ./.build/logdna-agent=/usr/bin/logdna-agent ./.build/scripts/init-script=/etc/init.d/logdna-agent ./.build/scripts/logrotate=/etc/logrotate.d/logdna-agent